# Generated by Django 2.0.6 on 2018-06-14 14:08

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThingWithTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=30)),
                ('description', markdownx.models.MarkdownxField()),
                ('long_text', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('published_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-published_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=30)),
                ('description', markdownx.models.MarkdownxField()),
                ('long_text', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('published_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-published_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
                ('path', models.TextField()),
                ('label', models.CharField(help_text='The name of the tag, without ancestors', max_length=255)),
                ('level', models.IntegerField(default=1, help_text='The level of the tag in the tree')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='frontend.TopicTags')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagTreeModel, models.Model),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('thingwithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frontend.ThingWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('frontend.thingwithtopics',),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('thingwithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frontend.ThingWithTopics')),
            ],
            options={
                'abstract': False,
            },
            bases=('frontend.thingwithtopics',),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('thingwithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frontend.ThingWithTopics')),
                ('doi', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('frontend.thingwithtopics',),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('thingwithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frontend.ThingWithTopics')),
                ('doi', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('url', models.URLField(unique=True)),
                ('citation', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('frontend.thingwithtopics',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('thingwithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frontend.ThingWithTopics')),
                ('doi', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('frontend.thingwithtopics',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('thingwithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frontend.ThingWithTopics')),
                ('doi', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('frontend.thingwithtopics',),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_tag',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, blank=True, force_lowercase=False, initial='"Health/Changing Behaviour", "Health/Data Science", "Science/Conflicts of Interest", "Science/Trial Reporting", Health/OpenPrescribing, Health/Policy, Health/RCTs, Health/Research, Health/Variation, Science/Policy, Science/RCTs, Science/Retractions, Science/TrialsTrackers', null=True, on_delete=django.db.models.deletion.CASCADE, space_delimiter=False, to='frontend.TopicTags', tree=True),
        ),
        migrations.AddField(
            model_name='thingwithtopics',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='"Health/Changing Behaviour", "Health/Data Science", "Science/Conflicts of Interest", "Science/Trial Reporting", Health/OpenPrescribing, Health/Policy, Health/RCTs, Health/Research, Health/Variation, Science/Policy, Science/RCTs, Science/Retractions, Science/TrialsTrackers', null=None, space_delimiter=False, to='frontend.TopicTags', tree=True),
        ),
        migrations.AlterUniqueTogether(
            name='topictags',
            unique_together={('slug', 'parent')},
        ),
        migrations.AddField(
            model_name='topic',
            name='authors',
            field=models.ManyToManyField(blank=True, to='frontend.Author'),
        ),
        migrations.AddField(
            model_name='thingwithtopics',
            name='authors',
            field=models.ManyToManyField(blank=True, to='frontend.Author'),
        ),
    ]
