# Generated by Django 2.0.6 on 2018-06-07 16:09

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20180607_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('navigation_title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, to='frontend.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tagulous_Author_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'abstract': False,
                'ordering': ('name',),
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_author_tags',
            unique_together={('slug',)},
        ),
        migrations.AddField(
            model_name='author',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='frontend.Tagulous_Author_tags'),
        ),
        migrations.AddField(
            model_name='blog',
            name='authors',
            field=models.ManyToManyField(blank=True, to='frontend.Author'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='authors',
            field=models.ManyToManyField(blank=True, to='frontend.Author'),
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, to='frontend.Author'),
        ),
        migrations.AddField(
            model_name='software',
            name='authors',
            field=models.ManyToManyField(blank=True, to='frontend.Author'),
        ),
        migrations.AddField(
            model_name='tool',
            name='authors',
            field=models.ManyToManyField(blank=True, to='frontend.Author'),
        ),
        migrations.AddField(
            model_name='topic',
            name='authors',
            field=models.ManyToManyField(blank=True, to='frontend.Author'),
        ),
    ]
