# Generated by Django 2.2.6 on 2019-11-20 14:54

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20191104_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='frontend.Page')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('overlay_text', models.CharField(blank=True, max_length=150)),
                ('overlay_url', models.URLField()),
                ('introduction', markdownx.models.MarkdownxField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('frontend.page',),
        ),
        migrations.AddField(
            model_name='page',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='"Health/Changing Behaviour", "Health/Data Science", "Science/Conflicts of Interest", "Science/Trial Reporting", Health/OpenPrescribing, Health/Policy, Health/RCTs, Health/Research, Health/Variation, Science/Policy, Science/RCTs, Science/Retractions, Science/TrialsTrackers', space_delimiter=False, to='frontend.TopicTags', tree=True),
        ),
    ]
