# Generated by Django 2.0.6 on 2018-06-13 08:24

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20180607_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', null=None, to='frontend.Tagulous_Author_tags'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', null=None, to='frontend.Tagulous_Topic_tags'),
        ),
    ]
