# Generated by Django 2.0.6 on 2018-06-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20180613_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
