# Generated by Django 2.2.6 on 2019-12-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20191120_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='colour_scheme',
            field=models.CharField(blank=True, choices=[['', ''], ['green', 'Green'], ['orange', 'Orange']], max_length=150),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member', to='frontend.Author'),
        ),
    ]
