# Generated by Django 2.0.6 on 2018-06-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20180613_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='abstract',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
