# Generated by Django 2.0.6 on 2018-06-13 09:51

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_paper_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='citation',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
