# Generated by Django 2.2.6 on 2020-03-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_series_seriesthing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='show_in_menu',
            new_name='show_in_home_menu',
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_footer_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_primary_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_secondary_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seriesthing',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serieses', to='frontend.ThingWithTopics'),
        ),
    ]
