# Generated by Django 2.0.6 on 2018-06-14 08:46

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20180613_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('-published_at',)},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-published_at',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-published_at',)},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='navigation_title',
            new_name='short_title',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='navigation_title',
            new_name='short_title',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='navigation_title',
            new_name='short_title',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='navigation_title',
            new_name='short_title',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='navigation_title',
            new_name='short_title',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='navigation_title',
            new_name='short_title',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='navigation_title',
            new_name='short_title',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='abstract',
        ),
        migrations.AddField(
            model_name='author',
            name='long_text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='long_text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='long_text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='long_text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='long_text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='long_text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='long_text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
