# Generated by Django 2.2.6 on 2020-03-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20200313_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(blank=True, choices=[['', 'Static page'], ['papers', 'Papers'], ['blog', 'Blog']], max_length=150),
        ),
    ]
