# Generated by Django 2.0.6 on 2018-06-14 12:06

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20180614_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterField(
            model_name='author',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', null=None, to='frontend.Tagulous_Author_tags'),
        ),
        migrations.AlterField(
            model_name='software',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='frontend.Tagulous_Software_tags'),
        ),
        migrations.AlterUniqueTogether(
            name='topics',
            unique_together={('slug',)},
        ),
        migrations.AddField(
            model_name='author',
            name='tags_two',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', null=None, to='frontend.Topics'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags_two',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', null=None, to='frontend.Topics'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='tags_two',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', null=None, to='frontend.Topics'),
        ),
        migrations.AddField(
            model_name='paper',
            name='tags_two',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', null=None, to='frontend.Topics'),
        ),
        migrations.AddField(
            model_name='software',
            name='tags_two',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', null=None, to='frontend.Topics'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tags_two',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', null=None, to='frontend.Topics'),
        ),
        migrations.AddField(
            model_name='topic',
            name='tags_two',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', null=None, to='frontend.Topics'),
        ),
    ]
