# Generated by Django 2.0.6 on 2018-06-14 12:16

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20180614_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tagulous_Author_tags',
        ),
        migrations.DeleteModel(
            name='Tagulous_Blog_tags',
        ),
        migrations.DeleteModel(
            name='Tagulous_Dataset_tags',
        ),
        migrations.DeleteModel(
            name='Tagulous_Paper_tags',
        ),
        migrations.DeleteModel(
            name='Tagulous_Software_tags',
        ),
        migrations.DeleteModel(
            name='Tagulous_Tool_tags',
        ),
        migrations.DeleteModel(
            name='Tagulous_Topic_tags',
        ),
        migrations.RemoveField(
            model_name='author',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='author',
            name='tags_two',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags_two',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='tags_two',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='tags_two',
        ),
        migrations.RemoveField(
            model_name='software',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='software',
            name='tags_two',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='tags_two',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tags_two',
        ),
        migrations.AddField(
            model_name='author',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='"Health/Changing Behaviour", "Health/Data Science", "Science/Conflicts of Interest", "Science/Trial Reporting", Health/OpenPrescribing, Health/Policy, Health/RCTs, Health/Research, Health/Variation, Science/Policy, Science/RCTs, Science/Retractions, Science/TrialsTrackers', null=None, space_delimiter=False, to='frontend.Topics', tree=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='"Health/Changing Behaviour", "Health/Data Science", "Science/Conflicts of Interest", "Science/Trial Reporting", Health/OpenPrescribing, Health/Policy, Health/RCTs, Health/Research, Health/Variation, Science/Policy, Science/RCTs, Science/Retractions, Science/TrialsTrackers', null=None, space_delimiter=False, to='frontend.Topics', tree=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='"Health/Changing Behaviour", "Health/Data Science", "Science/Conflicts of Interest", "Science/Trial Reporting", Health/OpenPrescribing, Health/Policy, Health/RCTs, Health/Research, Health/Variation, Science/Policy, Science/RCTs, Science/Retractions, Science/TrialsTrackers', null=None, space_delimiter=False, to='frontend.Topics', tree=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='"Health/Changing Behaviour", "Health/Data Science", "Science/Conflicts of Interest", "Science/Trial Reporting", Health/OpenPrescribing, Health/Policy, Health/RCTs, Health/Research, Health/Variation, Science/Policy, Science/RCTs, Science/Retractions, Science/TrialsTrackers', null=None, space_delimiter=False, to='frontend.Topics', tree=True),
        ),
        migrations.AddField(
            model_name='software',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='"Health/Changing Behaviour", "Health/Data Science", "Science/Conflicts of Interest", "Science/Trial Reporting", Health/OpenPrescribing, Health/Policy, Health/RCTs, Health/Research, Health/Variation, Science/Policy, Science/RCTs, Science/Retractions, Science/TrialsTrackers', null=None, space_delimiter=False, to='frontend.Topics', tree=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='"Health/Changing Behaviour", "Health/Data Science", "Science/Conflicts of Interest", "Science/Trial Reporting", Health/OpenPrescribing, Health/Policy, Health/RCTs, Health/Research, Health/Variation, Science/Policy, Science/RCTs, Science/Retractions, Science/TrialsTrackers', null=None, space_delimiter=False, to='frontend.Topics', tree=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topics',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=False, help_text='Enter a comma-separated tag string', initial='"Health/Changing Behaviour", "Health/Data Science", "Science/Conflicts of Interest", "Science/Trial Reporting", Health/OpenPrescribing, Health/Policy, Health/RCTs, Health/Research, Health/Variation, Science/Policy, Science/RCTs, Science/Retractions, Science/TrialsTrackers', null=None, space_delimiter=False, to='frontend.Topics', tree=True),
        ),
        migrations.AddField(
            model_name='topics',
            name='label',
            field=models.CharField(default='', help_text='The name of the tag, without ancestors', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topics',
            name='level',
            field=models.IntegerField(default=1, help_text='The level of the tag in the tree'),
        ),
        migrations.AddField(
            model_name='topics',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='frontend.Topics'),
        ),
        migrations.AddField(
            model_name='topics',
            name='path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='topics',
            unique_together={('slug', 'parent')},
        ),
    ]
